"use client"

import type { ClientPlatform, PlatformShortcutMap } from "@/lib/client-platform"
import { resolvePlatformShortcuts } from "@/lib/client-platform"

function renderShortcut(platform: ClientPlatform, shortcuts: PlatformShortcutMap) {
  return resolvePlatformShortcuts(shortcuts, platform).join(" / ")
}

function buildShortcutTable(platform: ClientPlatform) {
  const rows = [
    ["加粗", renderShortcut(platform, { windows: ["Ctrl+B"], mac: ["Cmd+B"], default: ["Ctrl+B"] })],
    ["斜体", renderShortcut(platform, { windows: ["Ctrl+I"], mac: ["Cmd+I"], default: ["Ctrl+I"] })],
    ["删除线", renderShortcut(platform, { windows: ["Alt+Shift+5"], mac: ["Cmd+Shift+5"], default: ["Alt+Shift+5"] })],
    ["高亮", renderShortcut(platform, { windows: ["Ctrl+X"], mac: ["Cmd+X"], default: ["Ctrl+X"] })],
    ["插入链接", renderShortcut(platform, { windows: ["Ctrl+K"], mac: ["Cmd+K"], default: ["Ctrl+K"] })],
    ["标题 / 正文", renderShortcut(platform, { windows: ["Ctrl+1-6 / Ctrl+0"], mac: ["Cmd+1-6 / Cmd+0"], default: ["Ctrl+1-6 / Ctrl+0"] })],
    ["引用", renderShortcut(platform, { windows: ["Ctrl+Shift+Q"], mac: ["Cmd+Shift+Q"], default: ["Ctrl+Shift+Q"] })],
    ["无序 / 有序列表", renderShortcut(platform, { windows: ["Ctrl+Shift+L / Ctrl+Shift+O"], mac: ["Cmd+Shift+L / Cmd+Shift+O"], default: ["Ctrl+Shift+L / Ctrl+Shift+O"] })],
    ["行内代码 / 代码块", renderShortcut(platform, { windows: ["Ctrl+Shift+` / Ctrl+Shift+K"], mac: ["Cmd+Shift+` / Cmd+Option+C"], default: ["Ctrl+Shift+` / Ctrl+Shift+K"] })],
    ["公式", renderShortcut(platform, { windows: ["Ctrl+Alt+M / Ctrl+Shift+M"], mac: ["Cmd+Option+M / Cmd+Option+B"], default: ["Ctrl+Alt+M / Ctrl+Shift+M"] })],
    ["表格 / 表格行移动", renderShortcut(platform, { windows: ["Ctrl+T / Alt+Up Down"], mac: ["Cmd+T / Option+Up Down"], default: ["Ctrl+T / Alt+Up Down"] })],
    ["图片上传", renderShortcut(platform, { windows: ["Ctrl+Shift+I"], mac: ["Cmd+Shift+I"], default: ["Ctrl+Shift+I"] })],
  ]

  return [
    "| 功能 | 快捷键 |",
    "| --- | --- |",
    ...rows.map(([name, shortcut]) => `| ${name} | ${shortcut} |`),
  ].join("\n")
}

export function buildMarkdownEditorHelp(platform: ClientPlatform) {
  return [
    "# Markdown 编辑帮助",
    "",
    "> 这套编辑器在 CommonMark 基础上，扩展了任务列表、公式、Mermaid、提示块、媒体标记、表情短码等能力。工具栏、快捷键和预览渲染使用的是同一套规则。",
    "",
    "## 快捷键总览",
    "",
    buildShortcutTable(platform),
    "",
    "## 基础文本格式",
    "",
    "- **加粗**：`**文本**`",
    "- *斜体*：`*文本*`",
    "- ~~删除线~~：`~~文本~~`",
    "- ==高亮==：`==文本==`",
    "- <u>下划线</u>：`<u>文本</u>`",
    "- 行内代码：`` `const value = 1` ``",
    "",
    "## 标题与段落",
    "",
    "```md",
    "# 一级标题",
    "## 二级标题",
    "### 三级标题",
    "",
    "普通正文段落",
    "```",
    "",
    "段落对齐支持以下 HTML 写法：",
    "",
    "```html",
    "<p align=\"left\">左对齐</p>",
    "<center>居中内容</center>",
    "<p align=\"right\">右对齐</p>",
    "<p align=\"justify\">两端对齐</p>",
    "```",
    "",
    "## 列表与任务",
    "",
    "```md",
    "- 无序列表",
    "- 第二项",
    "",
    "1. 有序列表",
    "2. 自动续写",
    "",
    "- [ ] 待办任务",
    "- [x] 已完成任务",
    "```",
    "",
    "- `Enter` 会自动续写列表项。",
    "- `Tab` / `Shift+Tab` 可调整列表层级。",
    "",
    "## 链接、图片与引用",
    "",
    "```md",
    "> 这里是一段引用",
    "",
    "[OpenAI](https://openai.com)",
    "![示例图片](/uploads/example.png)",
    "```",
    "",
    "图片支持工具栏上传、拖拽上传和粘贴上传。",
    "",
    "## 代码、公式与图表",
    "",
    "代码块可指定语言：",
    "",
    "```md",
    "```ts",
    "export function sum(a: number, b: number) {",
    "  return a + b",
    "}",
    "```",
    "```",
    "",
    "数学公式支持行内和块级：",
    "",
    "```md",
    "$E = mc^2$",
    "",
    "$$",
    "\\int_0^1 x^2 \\, dx",
    "$$",
    "```",
    "",
    "Mermaid 图表直接用代码块：",
    "",
    "```md",
    "```mermaid",
    "graph TD",
    "  A[开始] --> B{判断}",
    "  B -->|是| C[继续]",
    "  B -->|否| D[结束]",
    "```",
    "```",
    "",
    "## 表格",
    "",
    "```md",
    "| 列 1 | 列 2 | 列 3 |",
    "| --- | --- | --- |",
    "| 内容 A | 内容 B | 内容 C |",
    "```",
    "",
    "- 工具栏可以直接插入表格骨架。",
    "- 在表格行内使用快捷键可新增、删除、上下移动行。",
    "",
    "## 提示块与扩展语法",
    "",
    "提示块支持以下类型：`info`、`tip`、`warning`、`danger`、`success`。",
    "",
    "```md",
    ":::info 阅读提示",
    "这里是说明内容。",
    ":::",
    "",
    ":::warning 注意",
    "这里可以写风险提示。",
    ":::",
    "```",
    "",
    "Spoiler 折叠块支持以下语法：",
    "",
    "```md",
    ":::spoiler 剧透提示",
    "这里是默认折叠的内容。",
    "支持多段 Markdown，展开后再阅读。",
    ":::",
    "```",
    "",
    "- 工具栏里的 `剧透` 按钮会弹出菜单，可选插入折叠剧透或点击遮罩。",
    "",
    "其他已启用扩展：",
    "",
    "- 点击遮罩：`!!需要点击显示的内容!!`",
    "  渲染后会在原文字位置直接遮住内容，点击后原位显示。",
    "- 上标：`x^2^`",
    "- 下标：`H~2~O`",
    "- 插入标记：`++新增内容++`",
    "- 缩写：`*[HTML]: HyperText Markup Language`",
    "- 脚注：`这里有一个脚注[^1]`",
    "",
    "## 表情与媒体",
    "",
    "- 表情短码：`:smile:`、`:heart:`、`:rocket:`",
    "- 自定义媒体标记：`MEDIA::video::https://...`、`MEDIA::audio::https://...`、`MEDIA::iframe::https://...`",
    "- `iframe` 嵌入适合 Bilibili、网易云、YouTube、腾讯视频等站点。",
    "",
  ].join("\n")
}
