import { DEFAULT_FOOTER_LINKS } from "@/lib/shared/config-parsers"
import { DEFAULT_SITE_HEADER_APP_LINKS } from "@/lib/site-header-app-links"

const defaultFooterCopyrightText = `Rhex 论坛系统 ${new Date().getFullYear()}`

export const defaultSiteSettingsCreateInput = {

  siteName: "Rhex 论坛系统",
  siteSlogan: "专注长期讨论与高质量交流",
  siteDescription: "Rhex 论坛系统是一个适合开源部署的现代论坛基础站点，默认提供可维护的正式初始化数据。",
  siteLogoText: "Rhex 论坛系统",
  siteLogoPath: null,
  siteSeoKeywords: "Rhex,Rhex 论坛系统,论坛,社区,Next.js,Prisma",
  pointName: "积分",
  footerLinksJson: JSON.stringify(DEFAULT_FOOTER_LINKS),
  analyticsCode: null,
  postLinkDisplayMode: "SLUG",
  homeFeedPostListDisplayMode: "DEFAULT",
  homeSidebarStatsCardEnabled: true,
  friendLinksEnabled: true,
  friendLinkApplicationEnabled: true,
  friendLinkAnnouncement: "欢迎与本站交换友情链接，请先添加我方链接后再提交申请，我们会在 1-3 个工作日内完成审核。",
  checkInEnabled: true,
  checkInReward: 5,
  checkInMakeUpCardPrice: 0,
  checkInVipMakeUpCardPrice: 0,
  postOfflinePrice: 0,
  postOfflineVip1Price: 0,
  postOfflineVip2Price: 0,
  postOfflineVip3Price: 0,
  inviteRewardInviter: 0,



  inviteRewardInvitee: 0,
  registrationEnabled: true,
  registrationRequireInviteCode: false,
  registerInviteCodeEnabled: true,
  inviteCodePurchaseEnabled: false,
  inviteCodePrice: 0,
  registerCaptchaMode: "OFF",
  loginCaptchaMode: "OFF",
  turnstileSiteKey: null,
  nicknameChangePointCost: 0,
  postEditableMinutes: 10,
  commentEditableMinutes: 5,
  tippingEnabled: false,
  tippingDailyLimit: 3,
  tippingPerPostLimit: 1,
  tippingAmounts: "10,30,50,100",
  postRedPacketEnabled: false,
  postRedPacketMaxPoints: 100,
  postRedPacketDailyLimit: 100,
  heatViewWeight: 1,
  heatCommentWeight: 8,
  heatLikeWeight: 6,
  heatTipCountWeight: 10,
  heatTipPointsWeight: 1,
  heatStageThresholds: "0,80,180,320,520,780,1100,1500,2000",
  heatStageColors: "#4A4A4A,#808080,#9B8F7F,#B87333,#C4A777,#E8C547,#FFA500,#D96C3B,#C41E3A",
  registerEmailEnabled: false,
  registerEmailRequired: false,
  registerEmailVerification: false,
  registerPhoneEnabled: false,
  registerPhoneRequired: false,
  registerPhoneVerification: false,
  registerNicknameEnabled: true,
  registerNicknameRequired: false,
  registerGenderEnabled: false,
  registerGenderRequired: false,
  registerInviterEnabled: true,
  smtpEnabled: false,
  smtpHost: null,
  smtpPort: null,
  smtpUser: null,
  smtpPass: null,
  smtpFrom: null,
  smtpSecure: false,
  vipMonthlyPrice: 3000,
  vipQuarterlyPrice: 8000,
  vipYearlyPrice: 30000,
  uploadProvider: "local",
  uploadLocalPath: "uploads",
  uploadBaseUrl: null,
  uploadOssBucket: null,
  uploadOssRegion: null,
  uploadOssEndpoint: null,
  uploadRequireLogin: true,
  uploadAllowedImageTypes: "jpg,jpeg,png,gif,webp",
  uploadMaxFileSizeMb: 5,
  uploadAvatarMaxFileSizeMb: 2,
  markdownEmojiMapJson: JSON.stringify([
    { shortcode: "smile", label: "微笑", icon: "😀" },
    { shortcode: "heart", label: "爱心", icon: "❤️" },
    { shortcode: "rocket", label: "火箭", icon: "🚀" },
    { shortcode: "fire", label: "火焰", icon: "🔥" },
    { shortcode: "sparkles", label: "闪光", icon: "✨" },
  ]),
  headerAppLinksJson: JSON.stringify(DEFAULT_SITE_HEADER_APP_LINKS),
  headerAppIconName: "grid",
  appStateJson: JSON.stringify({
    __siteSettings: {
      registerNicknameLengths: {
        minLength: 1,
        maxLength: 20,
      },
      registerEmailWhitelist: {
        enabled: false,
        domains: [],
      },
      postSlugGeneration: {
        mode: "TITLE_TIMESTAMP",
      },
      siteBranding: {
        iconPath: "",
      },
      footerCopyright: {
        text: defaultFooterCopyrightText,
        brandingVisible: true,
      },
      imageWatermark: {
        enabled: false,
        text: "",
        position: "BOTTOM_RIGHT",
        opacity: 22,
        fontSize: 24,
        margin: 24,
        color: "#FFFFFF",
      },
      registrationEmailTemplates: {
        registerVerification: {
          subject: "{{siteName}} 验证码",
          text: "你的验证码是 {{code}}，10 分钟内有效。如非本人操作请忽略。",
          html: "<div style=\"font-family:Arial,sans-serif;line-height:1.7;color:#111\"><h2>{{siteName}} 验证码</h2><p>你的验证码是：</p><p style=\"font-size:28px;font-weight:700;letter-spacing:6px\">{{code}}</p><p>验证码 10 分钟内有效，如非本人操作请忽略。</p></div>",
        },
        resetPasswordVerification: {
          subject: "{{siteName}} 找回密码验证码",
          text: "用户 {{username}} 的找回密码验证码是 {{code}}，10 分钟内有效。如非本人操作，请尽快检查账号安全。",
          html: "<div style=\"font-family:Arial,sans-serif;line-height:1.7;color:#111\"><h2>{{siteName}} 找回密码</h2><p>账号：<strong>{{username}}</strong></p><p>你的找回密码验证码是：</p><p style=\"font-size:28px;font-weight:700;letter-spacing:6px\">{{code}}</p><p>验证码 10 分钟内有效。如非本人操作，请忽略此邮件并尽快检查账号安全。</p></div>",
        },
      },
      authPageShowcase: {
        enabled: true,
      },
      leftSidebarDisplay: {
        mode: "DEFAULT",
      },
      attachments: {
        uploadEnabled: false,
        downloadEnabled: false,
        minUploadLevel: 0,
        minUploadVipLevel: 0,
        allowedExtensions: ["zip", "rar", "7z", "pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "txt"],
        maxFileSizeMb: 20,
      },
    },
  }),
  sensitiveStateJson: "{}",

} as const
