ALTER TYPE "TaskConditionType" ADD VALUE IF NOT EXISTS 'FAVORITE_POST_COUNT';
ALTER TYPE "TaskConditionType" ADD VALUE IF NOT EXISTS 'FOLLOW_BOARD_COUNT';
ALTER TYPE "TaskConditionType" ADD VALUE IF NOT EXISTS 'FOLLOW_USER_COUNT';
ALTER TYPE "TaskConditionType" ADD VALUE IF NOT EXISTS 'FOLLOW_TAG_COUNT';
ALTER TYPE "TaskConditionType" ADD VALUE IF NOT EXISTS 'FOLLOW_POST_COUNT';
