import type {
  AddonActionHookName,
  AddonAsyncWaterfallHookName,
  AddonHookKind,
  AddonSlotKey,
  AddonWaterfallHookName,
} from "@/addons-host/types"

export type AddonExtensionPointKind = "slot" | AddonHookKind

export interface AddonExtensionPointCatalogEntry {
  name: string
  kind: AddonExtensionPointKind
  category: string
  scope: "global" | "page" | "service"
  summary: string
  returns: string
}

const slotCatalog: readonly AddonExtensionPointCatalogEntry[] = [
  { name: "auth.login.captcha", kind: "slot", category: "auth", scope: "page", summary: "在登录表单验证码区域插入 UI。", returns: "AddonRenderResult | null" },
  { name: "auth.login.form.after", kind: "slot", category: "auth", scope: "page", summary: "在登录表单主要字段后追加 UI 块。", returns: "AddonRenderResult | null" },
  { name: "auth.register.captcha", kind: "slot", category: "auth", scope: "page", summary: "在注册表单验证码区域插入 UI。", returns: "AddonRenderResult | null" },
  { name: "auth.register.form.after", kind: "slot", category: "auth", scope: "page", summary: "在注册表单主要字段后追加 UI 块。", returns: "AddonRenderResult | null" },
  { name: "post.create.captcha", kind: "slot", category: "post", scope: "page", summary: "在发帖页验证码区域插入 UI。", returns: "AddonRenderResult | null" },
  { name: "layout.head.before", kind: "slot", category: "layout", scope: "global", summary: "在全站 head 前段插入资源或标记。", returns: "AddonRenderResult | null" },
  { name: "layout.head.after", kind: "slot", category: "layout", scope: "global", summary: "在全站 head 尾段插入资源或标记。", returns: "AddonRenderResult | null" },
  { name: "layout.header.left", kind: "slot", category: "layout", scope: "global", summary: "在站点头部左侧区域插入内容。", returns: "AddonRenderResult | null" },
  { name: "layout.header.center", kind: "slot", category: "layout", scope: "global", summary: "在站点头部中部区域插入内容。", returns: "AddonRenderResult | null" },
  { name: "layout.header.right", kind: "slot", category: "layout", scope: "global", summary: "在站点头部右侧区域插入内容。", returns: "AddonRenderResult | null" },
  { name: "layout.footer.before", kind: "slot", category: "layout", scope: "global", summary: "在全站页脚主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "layout.footer.after", kind: "slot", category: "layout", scope: "global", summary: "在全站页脚主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "layout.body.start", kind: "slot", category: "layout", scope: "global", summary: "在 body 起始处插入内容。", returns: "AddonRenderResult | null" },
  { name: "layout.body.end", kind: "slot", category: "layout", scope: "global", summary: "在 body 结束前插入内容。", returns: "AddonRenderResult | null" },
  { name: "layout.sidebar.left.top", kind: "slot", category: "layout", scope: "global", summary: "在左侧边栏顶部插入内容。", returns: "AddonRenderResult | null" },
  { name: "layout.sidebar.left.bottom", kind: "slot", category: "layout", scope: "global", summary: "在左侧边栏底部插入内容。", returns: "AddonRenderResult | null" },
  { name: "layout.sidebar.right.top", kind: "slot", category: "layout", scope: "global", summary: "在右侧边栏顶部插入内容。", returns: "AddonRenderResult | null" },
  { name: "layout.sidebar.right.middle", kind: "slot", category: "layout", scope: "global", summary: "在右侧边栏中部插入内容。", returns: "AddonRenderResult | null" },
  { name: "layout.sidebar.right.bottom", kind: "slot", category: "layout", scope: "global", summary: "在右侧边栏底部插入内容。", returns: "AddonRenderResult | null" },
  { name: "home.right.top", kind: "slot", category: "home", scope: "page", summary: "在首页右侧栏顶部插入内容。", returns: "AddonRenderResult | null" },
  { name: "home.right.middle", kind: "slot", category: "home", scope: "page", summary: "在首页右侧栏中部插入内容。", returns: "AddonRenderResult | null" },
  { name: "home.right.bottom", kind: "slot", category: "home", scope: "page", summary: "在首页右侧栏底部插入内容。", returns: "AddonRenderResult | null" },
  { name: "board.right.top", kind: "slot", category: "board", scope: "page", summary: "在节点页右侧栏顶部插入内容。", returns: "AddonRenderResult | null" },
  { name: "board.right.middle", kind: "slot", category: "board", scope: "page", summary: "在节点页右侧栏中部插入内容。", returns: "AddonRenderResult | null" },
  { name: "board.right.bottom", kind: "slot", category: "board", scope: "page", summary: "在节点页右侧栏底部插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.header.before", kind: "slot", category: "post", scope: "page", summary: "在帖子详情头部信息区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.header.after", kind: "slot", category: "post", scope: "page", summary: "在帖子详情头部信息区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.author.row.before", kind: "slot", category: "post", scope: "page", summary: "在帖子作者行前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.author.row.after", kind: "slot", category: "post", scope: "page", summary: "在帖子作者行后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.author.meta.before", kind: "slot", category: "post", scope: "page", summary: "在帖子作者元信息区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.author.meta.after", kind: "slot", category: "post", scope: "page", summary: "在帖子作者元信息区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.author.verification.before", kind: "slot", category: "post", scope: "page", summary: "在帖子作者认证标识前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.author.verification.after", kind: "slot", category: "post", scope: "page", summary: "在帖子作者认证标识后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.author.name.before", kind: "slot", category: "post", scope: "page", summary: "在帖子作者用户名区域前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.author.name.after", kind: "slot", category: "post", scope: "page", summary: "在帖子作者用户名区域后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.author.badges.before", kind: "slot", category: "post", scope: "page", summary: "在帖子作者勋章区域前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.author.badges.after", kind: "slot", category: "post", scope: "page", summary: "在帖子作者勋章区域后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.body.before", kind: "slot", category: "post", scope: "page", summary: "在帖子正文前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.body.after", kind: "slot", category: "post", scope: "page", summary: "在帖子正文后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.sidebar.top", kind: "slot", category: "post", scope: "page", summary: "在帖子右侧栏顶部插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.sidebar.bottom", kind: "slot", category: "post", scope: "page", summary: "在帖子右侧栏底部插入内容。", returns: "AddonRenderResult | null" },
  { name: "comment.item.after", kind: "slot", category: "comment", scope: "page", summary: "在单条评论内容后插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.page.before", kind: "slot", category: "settings", scope: "page", summary: "在用户设置页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.page.after", kind: "slot", category: "settings", scope: "page", summary: "在用户设置页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.sidebar.top", kind: "slot", category: "settings", scope: "page", summary: "在用户设置页侧栏导航顶部插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.sidebar.bottom", kind: "slot", category: "settings", scope: "page", summary: "在用户设置页侧栏导航底部插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.content.before", kind: "slot", category: "settings", scope: "page", summary: "在当前设置分区内容前插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.content.after", kind: "slot", category: "settings", scope: "page", summary: "在当前设置分区内容后插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.profile.before", kind: "slot", category: "settings", scope: "page", summary: "在资料设置分区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.profile.after", kind: "slot", category: "settings", scope: "page", summary: "在资料设置分区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.invite.before", kind: "slot", category: "settings", scope: "page", summary: "在邀请中心分区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.invite.after", kind: "slot", category: "settings", scope: "page", summary: "在邀请中心分区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.post-management.before", kind: "slot", category: "settings", scope: "page", summary: "在帖子管理分区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.post-management.after", kind: "slot", category: "settings", scope: "page", summary: "在帖子管理分区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.board-applications.before", kind: "slot", category: "settings", scope: "page", summary: "在节点申请分区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.board-applications.after", kind: "slot", category: "settings", scope: "page", summary: "在节点申请分区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.level.before", kind: "slot", category: "settings", scope: "page", summary: "在我的等级分区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.level.after", kind: "slot", category: "settings", scope: "page", summary: "在我的等级分区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.badges.before", kind: "slot", category: "settings", scope: "page", summary: "在勋章中心分区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.badges.after", kind: "slot", category: "settings", scope: "page", summary: "在勋章中心分区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.verifications.before", kind: "slot", category: "settings", scope: "page", summary: "在账号认证分区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.verifications.after", kind: "slot", category: "settings", scope: "page", summary: "在账号认证分区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.points.before", kind: "slot", category: "settings", scope: "page", summary: "在积分明细分区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.points.after", kind: "slot", category: "settings", scope: "page", summary: "在积分明细分区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.follows.before", kind: "slot", category: "settings", scope: "page", summary: "在我的关注分区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "settings.follows.after", kind: "slot", category: "settings", scope: "page", summary: "在我的关注分区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "topup.page.before", kind: "slot", category: "topup", scope: "page", summary: "在积分充值页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "topup.page.after", kind: "slot", category: "topup", scope: "page", summary: "在积分充值页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "topup.payment.before", kind: "slot", category: "topup", scope: "page", summary: "在充值方案区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "topup.payment.after", kind: "slot", category: "topup", scope: "page", summary: "在充值方案区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "topup.redeem.before", kind: "slot", category: "topup", scope: "page", summary: "在兑换码区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "topup.redeem.after", kind: "slot", category: "topup", scope: "page", summary: "在兑换码区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "vip.page.before", kind: "slot", category: "vip", scope: "page", summary: "在 VIP 页面主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "vip.page.after", kind: "slot", category: "vip", scope: "page", summary: "在 VIP 页面主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "vip.hero.before", kind: "slot", category: "vip", scope: "page", summary: "在 VIP 顶部介绍区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "vip.hero.after", kind: "slot", category: "vip", scope: "page", summary: "在 VIP 顶部介绍区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "vip.actions.before", kind: "slot", category: "vip", scope: "page", summary: "在 VIP 购买操作区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "vip.actions.after", kind: "slot", category: "vip", scope: "page", summary: "在 VIP 购买操作区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "vip.levels.before", kind: "slot", category: "vip", scope: "page", summary: "在 VIP 等级权益列表前插入内容。", returns: "AddonRenderResult | null" },
  { name: "vip.levels.after", kind: "slot", category: "vip", scope: "page", summary: "在 VIP 等级权益列表后插入内容。", returns: "AddonRenderResult | null" },
  { name: "help.page.before", kind: "slot", category: "help", scope: "page", summary: "在帮助页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "help.page.after", kind: "slot", category: "help", scope: "page", summary: "在帮助页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "help.sidebar.before", kind: "slot", category: "help", scope: "page", summary: "在帮助页右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "help.sidebar.after", kind: "slot", category: "help", scope: "page", summary: "在帮助页右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "help.document.before", kind: "slot", category: "help", scope: "page", summary: "在帮助文档主内容前插入内容。", returns: "AddonRenderResult | null" },
  { name: "help.document.after", kind: "slot", category: "help", scope: "page", summary: "在帮助文档主内容后插入内容。", returns: "AddonRenderResult | null" },
  { name: "about.page.before", kind: "slot", category: "about", scope: "page", summary: "在关于页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "about.page.after", kind: "slot", category: "about", scope: "page", summary: "在关于页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "about.hero.before", kind: "slot", category: "about", scope: "page", summary: "在关于页顶部介绍区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "about.hero.after", kind: "slot", category: "about", scope: "page", summary: "在关于页顶部介绍区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "about.highlights.before", kind: "slot", category: "about", scope: "page", summary: "在关于页亮点说明区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "about.highlights.after", kind: "slot", category: "about", scope: "page", summary: "在关于页亮点说明区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "about.principles.before", kind: "slot", category: "about", scope: "page", summary: "在关于页社区原则区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "about.principles.after", kind: "slot", category: "about", scope: "page", summary: "在关于页社区原则区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "about.sidebar.before", kind: "slot", category: "about", scope: "page", summary: "在关于页右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "about.sidebar.after", kind: "slot", category: "about", scope: "page", summary: "在关于页右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "write.page.before", kind: "slot", category: "write", scope: "page", summary: "在发帖页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "write.page.after", kind: "slot", category: "write", scope: "page", summary: "在发帖页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "write.header.before", kind: "slot", category: "write", scope: "page", summary: "在发帖页卡片标题区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "write.header.after", kind: "slot", category: "write", scope: "page", summary: "在发帖页卡片标题区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.create.form.before", kind: "slot", category: "post", scope: "page", summary: "在发帖表单整体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.create.form.after", kind: "slot", category: "post", scope: "page", summary: "在发帖表单整体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.create.tools.before", kind: "slot", category: "post", scope: "page", summary: "在发帖基础设置区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.create.tools.after", kind: "slot", category: "post", scope: "page", summary: "在发帖基础设置区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.create.editor.before", kind: "slot", category: "post", scope: "page", summary: "在发帖正文编辑器前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.create.editor.after", kind: "slot", category: "post", scope: "page", summary: "在发帖正文编辑器后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.create.enhancements.before", kind: "slot", category: "post", scope: "page", summary: "在发帖增强功能区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.create.enhancements.after", kind: "slot", category: "post", scope: "page", summary: "在发帖增强功能区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.create.submit.before", kind: "slot", category: "post", scope: "page", summary: "在发帖提交操作区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "post.create.submit.after", kind: "slot", category: "post", scope: "page", summary: "在发帖提交操作区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "faq.page.before", kind: "slot", category: "faq", scope: "page", summary: "在 FAQ 页面主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "faq.page.after", kind: "slot", category: "faq", scope: "page", summary: "在 FAQ 页面主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "faq.tabs.before", kind: "slot", category: "faq", scope: "page", summary: "在 FAQ 顶部专题导航前插入内容。", returns: "AddonRenderResult | null" },
  { name: "faq.tabs.after", kind: "slot", category: "faq", scope: "page", summary: "在 FAQ 顶部专题导航后插入内容。", returns: "AddonRenderResult | null" },
  { name: "faq.content.before", kind: "slot", category: "faq", scope: "page", summary: "在 FAQ 正文内容区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "faq.content.after", kind: "slot", category: "faq", scope: "page", summary: "在 FAQ 正文内容区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "notifications.page.before", kind: "slot", category: "notification", scope: "page", summary: "在通知页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "notifications.page.after", kind: "slot", category: "notification", scope: "page", summary: "在通知页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "notifications.toolbar.before", kind: "slot", category: "notification", scope: "page", summary: "在通知工具区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "notifications.toolbar.after", kind: "slot", category: "notification", scope: "page", summary: "在通知工具区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "notifications.list.before", kind: "slot", category: "notification", scope: "page", summary: "在通知列表前插入内容。", returns: "AddonRenderResult | null" },
  { name: "notifications.list.after", kind: "slot", category: "notification", scope: "page", summary: "在通知列表后插入内容。", returns: "AddonRenderResult | null" },
  { name: "messages.page.before", kind: "slot", category: "message", scope: "page", summary: "在私信页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "messages.page.after", kind: "slot", category: "message", scope: "page", summary: "在私信页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "messages.header.before", kind: "slot", category: "message", scope: "page", summary: "在私信页标题区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "messages.header.after", kind: "slot", category: "message", scope: "page", summary: "在私信页标题区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "messages.sidebar.before", kind: "slot", category: "message", scope: "page", summary: "在私信会话侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "messages.sidebar.after", kind: "slot", category: "message", scope: "page", summary: "在私信会话侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "messages.thread.before", kind: "slot", category: "message", scope: "page", summary: "在私信会话正文前插入内容。", returns: "AddonRenderResult | null" },
  { name: "messages.thread.after", kind: "slot", category: "message", scope: "page", summary: "在私信会话正文后插入内容。", returns: "AddonRenderResult | null" },
  { name: "search.page.before", kind: "slot", category: "search", scope: "page", summary: "在搜索页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "search.page.after", kind: "slot", category: "search", scope: "page", summary: "在搜索页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "search.hero.before", kind: "slot", category: "search", scope: "page", summary: "在搜索页顶部搜索区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "search.hero.after", kind: "slot", category: "search", scope: "page", summary: "在搜索页顶部搜索区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "search.results.before", kind: "slot", category: "search", scope: "page", summary: "在搜索结果区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "search.results.after", kind: "slot", category: "search", scope: "page", summary: "在搜索结果区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "tags.page.before", kind: "slot", category: "tag", scope: "page", summary: "在标签广场页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "tags.page.after", kind: "slot", category: "tag", scope: "page", summary: "在标签广场页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "tags.hero.before", kind: "slot", category: "tag", scope: "page", summary: "在标签广场顶部介绍区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "tags.hero.after", kind: "slot", category: "tag", scope: "page", summary: "在标签广场顶部介绍区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "tags.content.before", kind: "slot", category: "tag", scope: "page", summary: "在标签广场内容区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "tags.content.after", kind: "slot", category: "tag", scope: "page", summary: "在标签广场内容区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "tags.sidebar.before", kind: "slot", category: "tag", scope: "page", summary: "在标签广场右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "tags.sidebar.after", kind: "slot", category: "tag", scope: "page", summary: "在标签广场右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "tag.page.before", kind: "slot", category: "tag", scope: "page", summary: "在单标签页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "tag.page.after", kind: "slot", category: "tag", scope: "page", summary: "在单标签页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "tag.hero.before", kind: "slot", category: "tag", scope: "page", summary: "在单标签页顶部介绍区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "tag.hero.after", kind: "slot", category: "tag", scope: "page", summary: "在单标签页顶部介绍区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "tag.content.before", kind: "slot", category: "tag", scope: "page", summary: "在单标签帖子流前插入内容。", returns: "AddonRenderResult | null" },
  { name: "tag.content.after", kind: "slot", category: "tag", scope: "page", summary: "在单标签帖子流后插入内容。", returns: "AddonRenderResult | null" },
  { name: "tag.sidebar.before", kind: "slot", category: "tag", scope: "page", summary: "在单标签右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "tag.sidebar.after", kind: "slot", category: "tag", scope: "page", summary: "在单标签右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "user.page.before", kind: "slot", category: "user", scope: "page", summary: "在用户主页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "user.page.after", kind: "slot", category: "user", scope: "page", summary: "在用户主页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "user.sidebar.before", kind: "slot", category: "user", scope: "page", summary: "在用户主页左侧资料栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "user.sidebar.after", kind: "slot", category: "user", scope: "page", summary: "在用户主页左侧资料栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "user.profile.before", kind: "slot", category: "user", scope: "page", summary: "在用户主页概览区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "user.profile.after", kind: "slot", category: "user", scope: "page", summary: "在用户主页概览区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "user.activity.before", kind: "slot", category: "user", scope: "page", summary: "在用户主页动态区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "user.activity.after", kind: "slot", category: "user", scope: "page", summary: "在用户主页动态区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.page.before", kind: "slot", category: "feed", scope: "page", summary: "在首页内容流主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.page.after", kind: "slot", category: "feed", scope: "page", summary: "在首页内容流主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.main.before", kind: "slot", category: "feed", scope: "page", summary: "在首页内容流列表前插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.main.after", kind: "slot", category: "feed", scope: "page", summary: "在首页内容流列表后插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.sidebar.before", kind: "slot", category: "feed", scope: "page", summary: "在首页右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.sidebar.after", kind: "slot", category: "feed", scope: "page", summary: "在首页右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.latest.before", kind: "slot", category: "feed", scope: "page", summary: "在首页/最新流专属内容前插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.latest.after", kind: "slot", category: "feed", scope: "page", summary: "在首页/最新流专属内容后插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.new.before", kind: "slot", category: "feed", scope: "page", summary: "在新贴流专属内容前插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.new.after", kind: "slot", category: "feed", scope: "page", summary: "在新贴流专属内容后插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.hot.before", kind: "slot", category: "feed", scope: "page", summary: "在热门流专属内容前插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.hot.after", kind: "slot", category: "feed", scope: "page", summary: "在热门流专属内容后插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.following.before", kind: "slot", category: "feed", scope: "page", summary: "在关注流专属内容前插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.following.after", kind: "slot", category: "feed", scope: "page", summary: "在关注流专属内容后插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.universe.before", kind: "slot", category: "feed", scope: "page", summary: "在宇宙流专属内容前插入内容。", returns: "AddonRenderResult | null" },
  { name: "feed.universe.after", kind: "slot", category: "feed", scope: "page", summary: "在宇宙流专属内容后插入内容。", returns: "AddonRenderResult | null" },
  { name: "board.page.before", kind: "slot", category: "board", scope: "page", summary: "在节点页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "board.page.after", kind: "slot", category: "board", scope: "page", summary: "在节点页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "board.hero.before", kind: "slot", category: "board", scope: "page", summary: "在节点页顶部介绍卡前插入内容。", returns: "AddonRenderResult | null" },
  { name: "board.hero.after", kind: "slot", category: "board", scope: "page", summary: "在节点页顶部介绍卡后插入内容。", returns: "AddonRenderResult | null" },
  { name: "board.content.before", kind: "slot", category: "board", scope: "page", summary: "在节点帖子流前插入内容。", returns: "AddonRenderResult | null" },
  { name: "board.content.after", kind: "slot", category: "board", scope: "page", summary: "在节点帖子流后插入内容。", returns: "AddonRenderResult | null" },
  { name: "board.sidebar.before", kind: "slot", category: "board", scope: "page", summary: "在节点页右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "board.sidebar.after", kind: "slot", category: "board", scope: "page", summary: "在节点页右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "collections.page.before", kind: "slot", category: "collection", scope: "page", summary: "在合集广场页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "collections.page.after", kind: "slot", category: "collection", scope: "page", summary: "在合集广场页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "collections.hero.before", kind: "slot", category: "collection", scope: "page", summary: "在合集广场顶部介绍区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "collections.hero.after", kind: "slot", category: "collection", scope: "page", summary: "在合集广场顶部介绍区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "collections.content.before", kind: "slot", category: "collection", scope: "page", summary: "在合集广场内容区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "collections.content.after", kind: "slot", category: "collection", scope: "page", summary: "在合集广场内容区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "collections.sidebar.before", kind: "slot", category: "collection", scope: "page", summary: "在合集广场右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "collections.sidebar.after", kind: "slot", category: "collection", scope: "page", summary: "在合集广场右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "collection.page.before", kind: "slot", category: "collection", scope: "page", summary: "在单合集页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "collection.page.after", kind: "slot", category: "collection", scope: "page", summary: "在单合集页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "collection.hero.before", kind: "slot", category: "collection", scope: "page", summary: "在单合集头部信息区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "collection.hero.after", kind: "slot", category: "collection", scope: "page", summary: "在单合集头部信息区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "collection.pending.before", kind: "slot", category: "collection", scope: "page", summary: "在单合集待审核区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "collection.pending.after", kind: "slot", category: "collection", scope: "page", summary: "在单合集待审核区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "collection.content.before", kind: "slot", category: "collection", scope: "page", summary: "在单合集已收录帖子区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "collection.content.after", kind: "slot", category: "collection", scope: "page", summary: "在单合集已收录帖子区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "collection.sidebar.before", kind: "slot", category: "collection", scope: "page", summary: "在单合集页右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "collection.sidebar.after", kind: "slot", category: "collection", scope: "page", summary: "在单合集页右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcements.page.before", kind: "slot", category: "announcement", scope: "page", summary: "在公告列表页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcements.page.after", kind: "slot", category: "announcement", scope: "page", summary: "在公告列表页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcements.hero.before", kind: "slot", category: "announcement", scope: "page", summary: "在公告列表页顶部说明区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcements.hero.after", kind: "slot", category: "announcement", scope: "page", summary: "在公告列表页顶部说明区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcements.content.before", kind: "slot", category: "announcement", scope: "page", summary: "在公告列表区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcements.content.after", kind: "slot", category: "announcement", scope: "page", summary: "在公告列表区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcement.page.before", kind: "slot", category: "announcement", scope: "page", summary: "在单公告页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcement.page.after", kind: "slot", category: "announcement", scope: "page", summary: "在单公告页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcement.hero.before", kind: "slot", category: "announcement", scope: "page", summary: "在单公告头部信息区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcement.hero.after", kind: "slot", category: "announcement", scope: "page", summary: "在单公告头部信息区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcement.content.before", kind: "slot", category: "announcement", scope: "page", summary: "在单公告正文区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "announcement.content.after", kind: "slot", category: "announcement", scope: "page", summary: "在单公告正文区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "history.page.before", kind: "slot", category: "history", scope: "page", summary: "在足迹页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "history.page.after", kind: "slot", category: "history", scope: "page", summary: "在足迹页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "history.panel.before", kind: "slot", category: "history", scope: "page", summary: "在足迹面板前插入内容。", returns: "AddonRenderResult | null" },
  { name: "history.panel.after", kind: "slot", category: "history", scope: "page", summary: "在足迹面板后插入内容。", returns: "AddonRenderResult | null" },
  { name: "friend-links.page.before", kind: "slot", category: "friend-link", scope: "page", summary: "在友情链接页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "friend-links.page.after", kind: "slot", category: "friend-link", scope: "page", summary: "在友情链接页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "friend-links.hero.before", kind: "slot", category: "friend-link", scope: "page", summary: "在友情链接页顶部说明区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "friend-links.hero.after", kind: "slot", category: "friend-link", scope: "page", summary: "在友情链接页顶部说明区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "friend-links.content.before", kind: "slot", category: "friend-link", scope: "page", summary: "在友情链接目录区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "friend-links.content.after", kind: "slot", category: "friend-link", scope: "page", summary: "在友情链接目录区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "funs.page.before", kind: "slot", category: "funs", scope: "page", summary: "在全部节点页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "funs.page.after", kind: "slot", category: "funs", scope: "page", summary: "在全部节点页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "funs.content.before", kind: "slot", category: "funs", scope: "page", summary: "在全部节点内容区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "funs.content.after", kind: "slot", category: "funs", scope: "page", summary: "在全部节点内容区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "funs.sidebar.before", kind: "slot", category: "funs", scope: "page", summary: "在全部节点页右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "funs.sidebar.after", kind: "slot", category: "funs", scope: "page", summary: "在全部节点页右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "badge.page.before", kind: "slot", category: "badge", scope: "page", summary: "在勋章详情页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "badge.page.after", kind: "slot", category: "badge", scope: "page", summary: "在勋章详情页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "badge.hero.before", kind: "slot", category: "badge", scope: "page", summary: "在勋章详情顶部介绍区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "badge.hero.after", kind: "slot", category: "badge", scope: "page", summary: "在勋章详情顶部介绍区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "badge.sidebar.before", kind: "slot", category: "badge", scope: "page", summary: "在勋章详情页右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "badge.sidebar.after", kind: "slot", category: "badge", scope: "page", summary: "在勋章详情页右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "terms.page.before", kind: "slot", category: "terms", scope: "page", summary: "在论坛协议页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "terms.page.after", kind: "slot", category: "terms", scope: "page", summary: "在论坛协议页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "terms.hero.before", kind: "slot", category: "terms", scope: "page", summary: "在论坛协议顶部介绍区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "terms.hero.after", kind: "slot", category: "terms", scope: "page", summary: "在论坛协议顶部介绍区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "terms.content.before", kind: "slot", category: "terms", scope: "page", summary: "在论坛协议正文区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "terms.content.after", kind: "slot", category: "terms", scope: "page", summary: "在论坛协议正文区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "terms.sidebar.before", kind: "slot", category: "terms", scope: "page", summary: "在论坛协议页右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "terms.sidebar.after", kind: "slot", category: "terms", scope: "page", summary: "在论坛协议页右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "prison.page.before", kind: "slot", category: "prison", scope: "page", summary: "在小黑屋页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "prison.page.after", kind: "slot", category: "prison", scope: "page", summary: "在小黑屋页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "prison.hero.before", kind: "slot", category: "prison", scope: "page", summary: "在小黑屋顶部说明区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "prison.hero.after", kind: "slot", category: "prison", scope: "page", summary: "在小黑屋顶部说明区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "prison.content.before", kind: "slot", category: "prison", scope: "page", summary: "在小黑屋名单区前插入内容。", returns: "AddonRenderResult | null" },
  { name: "prison.content.after", kind: "slot", category: "prison", scope: "page", summary: "在小黑屋名单区后插入内容。", returns: "AddonRenderResult | null" },
  { name: "prison.sidebar.before", kind: "slot", category: "prison", scope: "page", summary: "在小黑屋页右侧栏前插入内容。", returns: "AddonRenderResult | null" },
  { name: "prison.sidebar.after", kind: "slot", category: "prison", scope: "page", summary: "在小黑屋页右侧栏后插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.forgot-password.page.before", kind: "slot", category: "auth", scope: "page", summary: "在找回密码页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.forgot-password.page.after", kind: "slot", category: "auth", scope: "page", summary: "在找回密码页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.forgot-password.panel.before", kind: "slot", category: "auth", scope: "page", summary: "在找回密码表单卡片前插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.forgot-password.panel.after", kind: "slot", category: "auth", scope: "page", summary: "在找回密码表单卡片后插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.passkey.page.before", kind: "slot", category: "auth", scope: "page", summary: "在 Passkey 页面主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.passkey.page.after", kind: "slot", category: "auth", scope: "page", summary: "在 Passkey 页面主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.passkey.panel.before", kind: "slot", category: "auth", scope: "page", summary: "在 Passkey 面板前插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.passkey.panel.after", kind: "slot", category: "auth", scope: "page", summary: "在 Passkey 面板后插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.complete.page.before", kind: "slot", category: "auth", scope: "page", summary: "在第三方登录补全页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.complete.page.after", kind: "slot", category: "auth", scope: "page", summary: "在第三方登录补全页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.complete.panel.before", kind: "slot", category: "auth", scope: "page", summary: "在第三方登录补全面板前插入内容。", returns: "AddonRenderResult | null" },
  { name: "auth.complete.panel.after", kind: "slot", category: "auth", scope: "page", summary: "在第三方登录补全面板后插入内容。", returns: "AddonRenderResult | null" },
  { name: "topup.result.page.before", kind: "slot", category: "topup", scope: "page", summary: "在充值结果页主体前插入内容。", returns: "AddonRenderResult | null" },
  { name: "topup.result.page.after", kind: "slot", category: "topup", scope: "page", summary: "在充值结果页主体后插入内容。", returns: "AddonRenderResult | null" },
  { name: "topup.result.panel.before", kind: "slot", category: "topup", scope: "page", summary: "在充值结果面板前插入内容。", returns: "AddonRenderResult | null" },
  { name: "topup.result.panel.after", kind: "slot", category: "topup", scope: "page", summary: "在充值结果面板后插入内容。", returns: "AddonRenderResult | null" },
] as const

const actionHookCatalog: readonly AddonExtensionPointCatalogEntry[] = [
  { name: "auth.login.before", kind: "action", category: "auth", scope: "service", summary: "登录成功写入会话前执行副作用或拦截逻辑。", returns: "void" },
  { name: "auth.login.after", kind: "action", category: "auth", scope: "service", summary: "登录成功后执行副作用逻辑。", returns: "void" },
  { name: "auth.register.before", kind: "action", category: "auth", scope: "service", summary: "注册写入账户前执行副作用或拦截逻辑。", returns: "void" },
  { name: "auth.register.after", kind: "action", category: "auth", scope: "service", summary: "注册成功后执行副作用逻辑。", returns: "void" },
  { name: "auth.identity.bind.before", kind: "action", category: "auth", scope: "service", summary: "第三方身份绑定到现有账户前执行副作用或拦截逻辑。", returns: "void" },
  { name: "auth.identity.bind.after", kind: "action", category: "auth", scope: "service", summary: "第三方身份绑定完成后执行副作用逻辑。", returns: "void" },
  { name: "auth.identity.unbind.before", kind: "action", category: "auth", scope: "service", summary: "第三方身份解绑前执行副作用或拦截逻辑。", returns: "void" },
  { name: "auth.identity.unbind.after", kind: "action", category: "auth", scope: "service", summary: "第三方身份解绑后执行副作用逻辑。", returns: "void" },
  { name: "auth.password.change.before", kind: "action", category: "auth", scope: "service", summary: "已登录用户修改密码前执行副作用或拦截逻辑。", returns: "void" },
  { name: "auth.password.change.after", kind: "action", category: "auth", scope: "service", summary: "已登录用户修改密码后执行副作用逻辑。", returns: "void" },
  { name: "auth.password.reset.before", kind: "action", category: "auth", scope: "service", summary: "通过找回密码流程重置密码前执行副作用或拦截逻辑。", returns: "void" },
  { name: "auth.password.reset.after", kind: "action", category: "auth", scope: "service", summary: "通过找回密码流程重置密码后执行副作用逻辑。", returns: "void" },
  { name: "post.create.before", kind: "action", category: "post", scope: "service", summary: "帖子创建前执行副作用或拦截逻辑。", returns: "void" },
  { name: "post.create.after", kind: "action", category: "post", scope: "service", summary: "帖子创建成功后执行副作用逻辑。", returns: "void" },
  { name: "comment.create.before", kind: "action", category: "comment", scope: "service", summary: "评论创建前执行副作用或拦截逻辑。", returns: "void" },
  { name: "comment.create.after", kind: "action", category: "comment", scope: "service", summary: "评论创建成功后执行副作用逻辑。", returns: "void" },
  { name: "message.send.before", kind: "action", category: "message", scope: "service", summary: "私信发送前执行副作用或拦截逻辑。", returns: "void" },
  { name: "message.send.after", kind: "action", category: "message", scope: "service", summary: "私信发送成功后执行副作用逻辑。", returns: "void" },
  { name: "payment.paid.before", kind: "action", category: "payment", scope: "service", summary: "支付到账后的宿主处理前执行副作用逻辑。", returns: "void" },
  { name: "payment.paid.after", kind: "action", category: "payment", scope: "service", summary: "支付到账后执行副作用逻辑。", returns: "void" },
  { name: "invite-code.purchase.before", kind: "action", category: "invite", scope: "service", summary: "邀请码购买扣点前执行副作用或拦截逻辑。", returns: "void" },
  { name: "invite-code.purchase.after", kind: "action", category: "invite", scope: "service", summary: "邀请码购买成功后执行副作用逻辑。", returns: "void" },
  { name: "redeem-code.redeem.before", kind: "action", category: "redeem", scope: "service", summary: "兑换码核销前执行副作用或拦截逻辑。", returns: "void" },
  { name: "redeem-code.redeem.after", kind: "action", category: "redeem", scope: "service", summary: "兑换码核销成功后执行副作用逻辑。", returns: "void" },
  { name: "user.update.before", kind: "action", category: "user", scope: "service", summary: "用户资料更新写入前执行副作用或拦截逻辑。", returns: "void" },
  { name: "user.update.after", kind: "action", category: "user", scope: "service", summary: "用户资料更新后执行副作用逻辑。", returns: "void" },
  { name: "user.notification-settings.update.before", kind: "action", category: "user", scope: "service", summary: "用户通知设置写入前执行副作用或拦截逻辑。", returns: "void" },
  { name: "user.notification-settings.update.after", kind: "action", category: "user", scope: "service", summary: "用户通知设置更新后执行副作用逻辑。", returns: "void" },
  { name: "addon.config.changed.before", kind: "action", category: "system", scope: "service", summary: "插件配置写入前执行副作用或拦截逻辑。", returns: "void" },
  { name: "addon.config.changed.after", kind: "action", category: "system", scope: "service", summary: "插件配置变更后执行副作用逻辑。", returns: "void" },
  // ─── v2 扩展 hook ───
  // 认证
  { name: "auth.logout.before", kind: "action", category: "auth", scope: "service", summary: "用户登出前执行副作用或拦截逻辑（payload: { userId, username, sessionId? }）。", returns: "void" },
  { name: "auth.logout.after", kind: "action", category: "auth", scope: "service", summary: "用户登出成功后执行副作用逻辑。", returns: "void" },
  // 帖子
  { name: "post.update.before", kind: "action", category: "post", scope: "service", summary: "帖子更新前执行副作用或拦截逻辑（payload: { postId, editorId, changes }）。", returns: "void" },
  { name: "post.update.after", kind: "action", category: "post", scope: "service", summary: "帖子更新成功后执行副作用逻辑（含最新 post 快照）。", returns: "void" },
  { name: "post.delete.before", kind: "action", category: "post", scope: "service", summary: "帖子删除前执行副作用或拦截逻辑（payload: { postId, editorId, reason? }）。", returns: "void" },
  { name: "post.delete.after", kind: "action", category: "post", scope: "service", summary: "帖子删除成功后执行副作用逻辑。", returns: "void" },
  { name: "post.status.changed.after", kind: "action", category: "post", scope: "service", summary: "帖子可读状态变化后执行副作用逻辑（payload: { postId, editorId, previousStatus, nextStatus }）。", returns: "void" },
  { name: "post.like.after", kind: "action", category: "post", scope: "service", summary: "帖子点赞状态变化后执行副作用逻辑（payload: { postId, userId, liked, likeCount }）。", returns: "void" },
  { name: "post.favorite.toggle.after", kind: "action", category: "post", scope: "service", summary: "帖子收藏状态切换后执行副作用逻辑（payload: { postId, userId, favorited }）。", returns: "void" },
  // 评论
  { name: "comment.update.before", kind: "action", category: "comment", scope: "service", summary: "评论更新前执行副作用或拦截逻辑（payload: { commentId, editorId, changes }）。", returns: "void" },
  { name: "comment.update.after", kind: "action", category: "comment", scope: "service", summary: "评论更新成功后执行副作用逻辑（含最新 comment 快照）。", returns: "void" },
  { name: "comment.delete.before", kind: "action", category: "comment", scope: "service", summary: "评论删除前执行副作用或拦截逻辑（payload: { commentId, editorId, reason? }）。", returns: "void" },
  { name: "comment.delete.after", kind: "action", category: "comment", scope: "service", summary: "评论删除成功后执行副作用逻辑。", returns: "void" },
  { name: "comment.like.after", kind: "action", category: "comment", scope: "service", summary: "评论点赞状态变化后执行副作用逻辑（payload: { commentId, userId, liked, likeCount }）。", returns: "void" },
  // 用户关系
  { name: "user.follow.toggle.after", kind: "action", category: "user", scope: "service", summary: "关注 / 取关关系切换后执行副作用逻辑（payload: { followerId, followeeId, following }）。", returns: "void" },
  // 通知
  { name: "notification.create.before", kind: "action", category: "notification", scope: "service", summary: "通知写入前执行副作用或拦截逻辑（payload: { recipientId, type, payload }）。", returns: "void" },
  { name: "notification.create.after", kind: "action", category: "notification", scope: "service", summary: "通知写入成功后执行副作用逻辑（含 notification 快照）。", returns: "void" },
  // 积分
  { name: "points.change.after", kind: "action", category: "points", scope: "service", summary: "积分余额变化后执行副作用逻辑（payload: { userId, delta, balance, reason }）。", returns: "void" },
  // 上传
  { name: "upload.file.before", kind: "action", category: "upload", scope: "service", summary: "文件上传落盘前执行副作用或拦截逻辑（payload: { uploaderId, filename, mime, size }）。", returns: "void" },
  { name: "upload.file.after", kind: "action", category: "upload", scope: "service", summary: "文件上传完成后执行副作用逻辑（payload 含 fileId/url）。", returns: "void" },
  // addon 生命周期
  { name: "addon.installed.after", kind: "action", category: "system", scope: "service", summary: "插件安装完成后执行副作用逻辑（payload: { addonId, version }）。", returns: "void" },
  { name: "addon.uninstalled.after", kind: "action", category: "system", scope: "service", summary: "插件卸载完成后执行副作用逻辑。", returns: "void" },
  { name: "addon.enabled.after", kind: "action", category: "system", scope: "service", summary: "插件启用后执行副作用逻辑。", returns: "void" },
  { name: "addon.disabled.after", kind: "action", category: "system", scope: "service", summary: "插件禁用后执行副作用逻辑。", returns: "void" },
  // 搜索
  { name: "search.query.after", kind: "action", category: "search", scope: "service", summary: "搜索查询执行后执行副作用逻辑（payload: { userId?, query, scope, resultCount }）。", returns: "void" },
] as const

const waterfallHookCatalog: readonly AddonExtensionPointCatalogEntry[] = [
  { name: "post.slug.value", kind: "waterfall", category: "post", scope: "service", summary: "串行改写帖子最终 slug。", returns: "string" },
  // ─── v2 扩展 hook ───
  { name: "post.title.value", kind: "waterfall", category: "post", scope: "service", summary: "串行改写帖子标题（落库前；可用于敏感词替换、自动加标记等）。", returns: "string" },
  { name: "comment.content.value", kind: "waterfall", category: "comment", scope: "service", summary: "串行改写评论内容（写入前；可用于签名补全、文本规范化等）。", returns: "string" },
  { name: "user.displayName.value", kind: "waterfall", category: "user", scope: "service", summary: "串行改写用户展示名（用于列表/详情渲染前的显示加工）。", returns: "string" },
  { name: "user.avatar.url.value", kind: "waterfall", category: "user", scope: "service", summary: "串行改写用户头像 URL（可插入 CDN 前缀、占位头像等）。", returns: "string" },
  { name: "search.query.normalize", kind: "waterfall", category: "search", scope: "service", summary: "串行规范化搜索关键词（大小写、同义词、繁简转换等）。", returns: "string" },
  { name: "seo.meta.title", kind: "waterfall", category: "seo", scope: "service", summary: "串行改写 SEO <title>。", returns: "string" },
  { name: "seo.meta.description", kind: "waterfall", category: "seo", scope: "service", summary: "串行改写 SEO meta description。", returns: "string" },
  { name: "breadcrumb.items", kind: "waterfall", category: "navigation", scope: "service", summary: "串行改写当前页面面包屑条目数组。", returns: "AddonBreadcrumbItem[]" },
] as const

const asyncWaterfallHookCatalog: readonly AddonExtensionPointCatalogEntry[] = [
  { name: "navigation.primary.items", kind: "asyncWaterfall", category: "navigation", scope: "service", summary: "串行改写站点主导航项数组。", returns: "NavigationItem[]" },
  { name: "home.sidebar.hot-topics.items", kind: "asyncWaterfall", category: "home", scope: "service", summary: "串行改写首页右栏热点帖子列表。", returns: "HomeSidebarHotTopic[]" },
  { name: "settings.post-management.tabs", kind: "asyncWaterfall", category: "settings", scope: "service", summary: "串行扩展用户设置页“帖子管理”的插件 tab 列表。", returns: "AddonSettingsPostManagementTab[]" },
  // ─── v2 扩展 hook ───
  { name: "feed.posts.items", kind: "asyncWaterfall", category: "post", scope: "service", summary: "串行改写帖子流（首页 / 分类 / 搜索结果列表），可插入广告位、置顶项、重排序。", returns: "AddonPostRecord[]" },
  { name: "search.results.rerank", kind: "asyncWaterfall", category: "search", scope: "service", summary: "串行对搜索结果重排序（含 query / scope 上下文）。", returns: "AddonSearchResultItem[]" },
  { name: "notification.dispatch.targets", kind: "asyncWaterfall", category: "notification", scope: "service", summary: "串行改写单条通知的分发目标（站内 / 邮件 / 其他通道）。", returns: "AddonNotificationDispatchTarget[]" },
  { name: "sitemap.entries", kind: "asyncWaterfall", category: "seo", scope: "service", summary: "串行扩展 sitemap.xml 条目列表。", returns: "AddonSitemapEntry[]" },
  { name: "post.related.items", kind: "asyncWaterfall", category: "post", scope: "service", summary: "串行改写帖子详情页相关推荐列表。", returns: "AddonPostRecord[]" },
  { name: "post.content.render", kind: "asyncWaterfall", category: "post", scope: "service", summary: "串行改写帖子正文渲染后的 HTML（代码高亮、LaTeX、Mermaid、表格美化等）。", returns: "string" },
] as const

export const ADDON_EXTENSION_POINT_CATALOG: readonly AddonExtensionPointCatalogEntry[] = [
  ...slotCatalog,
  ...actionHookCatalog,
  ...waterfallHookCatalog,
  ...asyncWaterfallHookCatalog,
] as const

const slotNameSet = new Set<string>(slotCatalog.map((item) => item.name))
const actionHookNameSet = new Set<string>(actionHookCatalog.map((item) => item.name))
const waterfallHookNameSet = new Set<string>(waterfallHookCatalog.map((item) => item.name))
const asyncWaterfallHookNameSet = new Set<string>(asyncWaterfallHookCatalog.map((item) => item.name))

export function isKnownAddonSlotName(name: string): name is AddonSlotKey {
  return slotNameSet.has(name)
}

export function isKnownAddonActionHookName(name: string): name is AddonActionHookName {
  return actionHookNameSet.has(name)
}

export function isKnownAddonWaterfallHookName(name: string): name is AddonWaterfallHookName {
  return waterfallHookNameSet.has(name)
}

export function isKnownAddonAsyncWaterfallHookName(name: string): name is AddonAsyncWaterfallHookName {
  return asyncWaterfallHookNameSet.has(name)
}

export function listAddonExtensionPointCatalog(kind?: AddonExtensionPointKind): AddonExtensionPointCatalogEntry[] {
  return kind
    ? ADDON_EXTENSION_POINT_CATALOG.filter((item) => item.kind === kind)
    : [...ADDON_EXTENSION_POINT_CATALOG]
}
